- examples/javascript/graphql/src/index.js
- examples/typescript/graphql-apollo-server/src/index.ts
- examples/typescript/graphql-auth/src/index.ts
- examples/typescript/graphql/src/index.ts
Fix examples based on a breaking change on the latest nexus-prisma
> Fix nexusPrismaMethod -> nexusPrismaPlugin

- packages/photon/src/runtime/utils/printDatasources.ts
https://github.com/prisma/prisma2/issues/1
> Rename postgres to postgresql.

- packages/photon/src/generation/TSClient.ts
- packages/photon/src/runtime/query.ts
Fixes #148 
However, I don't know how to update the snapshots/tests
> Allow null on updateInputs

- README.md
> Fix API examples in README

- examples/typescript/rest-express/src/index.ts
because in the last preview version its fixed and i removed that TODO description And Comment.
Thank you
> docs(examples): remove comments and description from line 26

- packages/fetch-engine/package.json
- packages/fetch-engine/src/download.ts
- packages/fetch-engine/src/downloadZip.ts
- packages/fetch-engine/src/getLatestAlphaTag.ts
- packages/fetch-engine/src/getProxyAgent.ts
- packages/fetch-engine/src/index.ts
- packages/fetch-engine/src/util.ts
- packages/fetch-engine/yarn.lock
Adds HTTP proxy support
Fixes https://github.com/prisma/prisma2/issues/506
> feat: proxy agent

- packages/get-platform/src/getPlatform.ts
- packages/get-platform/src/test/distros.ts
- packages/get-platform/src/test/getPlatform.ts
- packages/get-platform/src/test/openssl.ts
- packages/get-platform/src/test/run.ts
> fix(get-platform): refactor getPlatform, add unit tests

- packages/photon/src/generation/TSClient.ts
> TSClient: Exposes model select/include utility types

- packages/photon/examples/blog/prisma/schema.prisma
- packages/photon/examples/brewery/schema.prisma
- packages/photon/examples/listings/prisma/schema.prisma
Change needed since preview 19 @timsuchanek
> fix(photon): remove @unique for @id fields in examples

- README.md
> Add direct link to prisma-examples repo

- packages/engine-core/src/NodeEngine.ts
- packages/photon/src/generation/generateClient.ts
- packages/photon/tsconfig.json
> Perf improvements

- packages/engine-core/src/NodeEngine.ts
- packages/photon/fixtures/blog/main.ts
- packages/photon/src/__tests__/runtime-tests/blog/index.js
- packages/photon/src/generation/TSClient.ts
> fix(photon): allow reconnecting after disconnect

- packages/photon/README.md
- packages/photon/fixtures/blog/prisma/schema.prisma
- packages/photon/src/__tests__/runtime-tests/blog/index.js
- packages/photon/src/generation/TSClient.ts
- packages/photon/src/generation/utils.ts
with internal measurePerformance boolean
> Make collectTimestamps configurable

- packages/engine-core/src/NodeEngine.ts
- packages/photon/src/generation/TSClient.ts
> Add rustEngine time elapsed header into collectTimestamps 

- packages/engine-core/src/NodeEngine.ts
@timsuchanek I just fixed a little typo I found while sweeping through the last commits :)
> fix: correct typo

- packages/engine-core/src/NodeEngine.ts
- packages/photon/fixtures/blog/main.ts
- packages/photon/src/__tests__/runtime-tests/blog/index.js
- packages/photon/src/generation/TSClient.ts
- packages/photon/src/runtime/query.ts
See https://github.com/prisma/prisma-client-js/issues/455
Can be used like this
```js
const rawQuery = await prisma.raw`SELECT * FROM Posts`
```
> Implement prisma.raw

- packages/photon/src/__tests__/runtime-tests/blog/index.js
- packages/photon/src/generation/TSClient.ts
@nikolasburk will need to update the docs when merged.
> Allow .raw('') and .raw``

- packages/photon/package.json
- packages/photon/src/__tests__/runtime-tests/blog/index.js
- packages/photon/src/generation/TSClient.ts
- packages/photon/src/generation/generateClient.ts
- packages/photon/src/runtime/index.ts
- packages/photon/src/runtime/query.ts
> .raw`` template literal API with parameters

- packages/photon/package.json
See also https://github.com/prisma/prisma2/pull/1958
> Add description and keywords for npm search

- packages/photon/fixtures/blog/main.ts
- packages/photon/src/__tests__/runtime-tests/blog/index.js
- packages/photon/src/__tests__/types/blog/index.ts
- packages/photon/src/generation/TSClient.ts
- packages/photon/src/runtime/getPrismaClient.ts
- packages/photon/src/runtime/query.ts
- packages/photon/src/runtime/utils/printStack.ts
> Parameterized count

- packages/photon/fixtures/enums/main.ts
- packages/photon/fixtures/enums/prisma/schema.prisma
- packages/photon/src/__tests__/__snapshots__/include.test.ts.snap
- packages/photon/src/__tests__/include.test.ts
- packages/photon/src/__tests__/types/blog/index.ts
- packages/photon/src/fixtures/blog.ts
- packages/photon/src/generation/TSClient.ts
- packages/photon/src/runtime/query.ts
> Disallow include for model without relation

- packages/photon/fixtures/blog/main.ts
- packages/photon/fixtures/blog/prisma/schema.prisma
- packages/photon/src/__tests__/types/blog/index.ts
- packages/photon/src/generation/TSClient.ts
> Fix deep include with orderBy

- .github/stale.yml
Ref: https://github.com/prisma/prisma/pull/3096
> chore: Add stalebot

- .github/ISSUE_TEMPLATE/bug_report.md
Ref: https://github.com/prisma/prisma/pull/2888
> Update issue template to move down the Prisma version

- .github/workflows/label-stale-issues.yml
closes: https://github.com/prisma/prisma/issues/3112
> chore: update to stable stale action
